export let langRu = {
  'main': 'главная',
  'game': 'игра',
  'gallery': 'галерея',
  'main-title': '<span class="logo-color">Наш сайт </span>поможет тебе узнать о <span class="logo-color">Птицах</span>',
  'acquaintance': 'Познакомьтесь со всеми видами птиц и станьте частью нашего сообщества любителей птиц и фотографии',
  'play': 'Играть',
  'parrot': 'Попугай',
  'about-parrot': 'Попугаи насчитывают около 115 видов, которые являются семеноядными небольшого размера, стройного телосложения и длинных, сужающихся к верху хвостов.',
  'about-us': 'О нас',
  'more-about-us': 'Больше узнать о <span class="logo-color">птицах</span> здесь',
  'learn-more': 'Узнать Подробнее',
  'want-play': 'Хочешь попробовать сыграть?',
  'contacts': 'Контакты',
  'warm-up': 'Разминка',
  'sparrows': 'Воробьиные',
  'forest-birds': 'Лесные птицы',
  'songbirds': 'Певчие птицы',
  'birds-of-prey': 'Хищные птицы',
  'seabirds': 'Морские птицы',
  'next-level': 'Следующий уровень',
  'congratulations': 'Поздравляю!',
  'try-again': 'Попробовать еще раз',
  'score': 'Счет: 0',
}

export let langEng = {
  'main': 'Main',
  'game': 'Game',
  'gallery': 'Gallery',
  'main-title': '<span class="logo-color">BirdSong</span> Helps you to know about <span class="logo-color">Birds</span>',
  'acquaintance': 'Get to know all kinds of birds and become a part of our community of bird lovers and photography',
  'play': 'Play',
  'parrot': 'Parrot',
  'about-parrot': 'Parrot comprise about 115 species of birds that are seed-eating parrots of small size, slender build, and long, tapering tails',
  'about-us': 'About us',
  'more-about-us': 'Learn more about <span class="logo-color">birds</span> here',
  'learn-more': 'Learn more',
  'want-play': 'Do you want to play?',
  'contacts': 'Contacts',
  'warm-up': 'Warm-up',
  'sparrows': 'Sparrows',
  'forest-birds': 'Forest birds',
  'songbirds': 'Songbirds',
  'birds-of-prey': 'Birds of prey',
  'seabirds': 'Seabirds',
  'next-level': 'Next Level',
  'congratulations': 'Congratulations!',
  'try-again': 'Try again',
  'score': 'Score: 0',
}